### ISSUE TITLE
Continue Prototype

### ISSUE THREAD

**Issue by gdeusdara** [UnBArqDsw/2020.1_G2_TCLDL#54]

**Comment by Mikhaelle** [comment]
Use the issue to discuss solutions and implementations

Points given by stakeholders, raised by Gabriel and placed in the telegram group:

1) The home page will not be the one we have the list of papers, but the one I will send the print below:
![948199cd-956d-48fe-be32-c0a90426003d](https://user-images.githubusercontent.com/22429549/93732871-adac0c80-fba9-11ea-852f-fe1ff2f60e71.jpg)

2)On the same previous page they suggested some changes:
   - Add a graph with tabs where we can browse the graphs for each domain. For this, we will have to modify this page a little.

3) The page of papers that will no longer be the home will still exist, however, a reference will be created there in the navbar to go to it. Like a page called "New papers".

4) We have to think of a better name for "Browse the State of the Art"

5)This page will also undergo some modifications:

- This side text would come out (we would gain more space on the screen).
- The graph here would also be a tab graph, where we would switch from performance x computing power to performance x year;
- Because "Computing power" is a somewhat complex variable and there is a calculation behind it, we would put that little pop up of the "i" to have a description of what the variable would be.

![c8b99757-3333-404b-9322-24419b8cbfdd](https://user-images.githubusercontent.com/22429549/93732983-01b6f100-fbaa-11ea-9565-f4678e415787.jpg)

6) About the charts, he gave a very good suggestion about the visualization in the perf x year chart. Where, in papers that are not reported, the computational power is an empty circle and those that reported, are one with filled circles.

7) Currently we have basically 2 features for users: submit paper and review them in the case of the admin. We have to create a third one that would be like "proposing data modification". This is due to the following reason: several papers the authors do not disclose how much computing power was used by them to run the model. With this new feature they can go there and send us just that data (or, in case, for example, they realize that our data is wrong, they send us the correct ones). It would be like an "edit".

8) Add in Prototype: Upload and Download for Data and Graphs.

**Comment by lorryaze** [comment]
This issue need to be done this week, because it's already open for 14 days!
